### ISSUE TITLE
Tramp integration

### ISSUE THREAD

**Issue by skye** [h/find-file-in-repository#17] opened 2017-03-29 21:10 UTC
find-file-in-repository doesn't appear to work if you're accessing a remote checkout via tramp (e.g. if you're visiting a file like /ssh:me@remotemachine:path/to/repo).

When I try it, I get weird options including the following:
`/bin/bash: line 0: cd: /ssh:<path to my git root>: No such file or directory`

**Comment by h** [comment] 2017-03-29 23:01
This would require either 1) executing git on the remote machine, or 2) falling back on default behavior while using tramp. Pull requests welcome :)

**Comment by apresta** [comment] 2019-03-28 04:17
Actually, ffir somewhat works for me in TRAMP, although with a bug: I get the same error as Skye, which means the paths returned by ffir are relative to the default-directory. This is usable but obviously not the expected behavior.

Core Emacs functions do a good job of supporting TRAMP transparently, but the problem is that building shell commands with string concatenation (see ffir-format-str) bypasses that.
A more robust way is to set default-directory locally to the working-dir when calling shell-command. This also simplifies the code a bit.
I'll send a pull request.

**Comment by apresta** [comment] 2019-03-28 04:22
https://github.com/h/find-file-in-repository/pull/19

**Comment by h** [comment] 2021-02-25 19:38
Closed by #19

**Closed by h** 2021-02-25 19:38 UTC
